# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start Services
      run: docker-compose up -d

    - name: Wait for Services to be Ready
      run: |
        echo "Waiting for services to be ready..."
        sleep 10

    - name: Test
      run: go test -v ./...

    - name: Tear Down Services
      if: always()
      run: docker-compose down -v
