# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
      
    - name: Run main in the background
      run: |
          nohup go run main.go & # Run main.go in the background
          echo $! > main_pid.txt # Save the process ID to a file
    - name: Wait for main to start
      run: sleep 5 # Adjust this based on how long main.go takes to be ready
      
    - name: Test
      run: go test -v ./...

    - name: Stop main
      run: |
        kill $(cat main_pid.txt) || echo "Process already terminated"
